dan_courses_sp = {
    "1st Dan": {
        "7th style": [".59", "The Beauty of Silence", "SOLID GOLD", "Holic"],
        "8th style": [".59", "V35", "夜のサングラス", "Holic"],
        "9th style": ["Foundation of our love", ".59", "Radical Faith", "Dreamin' Sun"],
        "10th style": ["Foundation of our love", ".59", "I Was The One (80's EUROBEAT STYLE)", "DoLL"],
        "11 IIDX RED": ["Foundation of our love", ".59", "I Was The One (80's EUROBEAT STYLE)", "KI・SE・KI (IIDX RED EDIT)"],
        "12 HAPPY SKY": ["Foundation of our love", ".59", "Under the Sky", "I Was The One (80's EUROBEAT STYLE)"],
        "13 DistorteD": ["Foundation of our love", ".59", "Under the Sky", "I Was The One (80's EUROBEAT STYLE)"],
        "14 GOLD": ["Foundation of our love", ".59", "Under the Sky", "I Was The One (80's EUROBEAT STYLE)"],
        "15 DJ TROOPERS": ["Foundation of our love", ".59", "Under the Sky", "I Was The One (80's EUROBEAT STYLE)"],
        "16 EMPRESS": ["Blind Justice ～Torn souls, Hurt Faiths～", ".59", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "17 SIRIUS": ["Blind Justice ～Torn souls, Hurt Faiths～", "with you…", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "18 Resort Anthem": ["Blind Justice ～Torn souls, Hurt Faiths～", "with you…", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "19 Lincle": ["Blind Justice ～Torn souls, Hurt Faiths～", "with you…", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "20 tricoro": ["Blind Justice ～Torn souls, Hurt Faiths～", "with you…", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "21 SPADA": ["Blind Justice ～Torn souls, Hurt Faiths～", "with you…", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "22 PENDUAL": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "23 copula": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "24 SINOBUZ": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "25 CANNON BALLERS": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "26 Rootage": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "27 HEROIC VERSE": ["Blind Justice ～Torn souls, Hurt Faiths～", "Funny shuffle", "GOLD RUSH", "I Was The One (80's EUROBEAT STYLE)"],
        "28 BISTROVER": ["Last Dance", "Level One", "You'll say \"Now!\"", "HAPPY☆ANGEL"],
        "29 CastHour": ["Red. by Full Metal Jacket", "Last Dance", "Crank It", "HAPPY☆ANGEL"],
        "30 RESIDENT": ["Double Dribble", "Last Dance", "Crank It", "HAPPY☆ANGEL"],
        "31 EPOLIS": ["EDEN", "STARLIGHT DANCEHALL", "IDOL syndrome.", "HAPPY☆ANGEL"],
        "32 Pinky Crush": ["EDEN", "STARLIGHT DANCEHALL", "IDOL syndrome.", "HAPPY☆ANGEL"],
    },

    "2nd Dan": {
        "7th style": ["D2R", "Abyss", "Final Count Down(MTO CRY BABY STYLE)", "CAN'T STOP FALLIN'IN LOVE"],
        "8th style": ["Drivin'", "Abyss", "Attitude", "Final Count Down(MTO CRY BABY STYLE)"],
        "9th style": ["Monkey Dance", "Abyss", "Your Body", "Be Rock U (1998 burst style)"],
        "10th style": ["Monkey Dance", "Abyss", "Your Body", "Final Count Down(MTO CRY BABY STYLE)"],
        "11 IIDX RED": ["Monkey Dance", "Abyss", "Les filles balancent", "Final Count Down(MTO CRY BABY STYLE)"],
        "12 HAPPY SKY": ["Monkey Dance", "Abyss", "HAPPY☆ANGEL", "Final Count Down(MTO CRY BABY STYLE)"],
        "13 DistorteD": ["Monkey Dance", "Abyss", "DEEP ROAR", "Zenius -I- vanisher"],
        "14 GOLD": ["Monkey Dance", "Abyss", "Don't let it go", "Zenius -I- vanisher"],
        "15 DJ TROOPERS": ["Monkey Dance", "Zenius -I- vanisher", "Don't let it go", "Abyss"],
        "16 EMPRESS": ["Monkey Dance", "Zenius -I- vanisher", "Don't let it go", "Abyss"],
        "17 SIRIUS": ["Monkey Dance", "Zenius -I- vanisher", "山岡晃の「クイズ！家事都合！」", "Abyss"],
        "18 Resort Anthem": ["Monkey Dance", "Zenius -I- vanisher", "山岡晃の「クイズ！家事都合！」", "Abyss"],
        "19 Lincle": ["Monkey Dance", "Zenius -I- vanisher", "山岡晃の「クイズ！家事都合！」", "Abyss"],
        "20 tricoro": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "21 SPADA": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "22 PENDUAL": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "23 copula": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "24 SINOBUZ": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "25 CANNON BALLERS": ["Monkey Dance", "Zenius -I- vanisher", "Drive Me Crazy", "Abyss"],
        "26 Rootage": ["Monkey Dance", "Sweet Clapper", "Zenius -I- vanisher", "Abyss"],
        "26 Rootage (offline)": ["Monkey Dance", "bloomin' feeling", "Zenius -I- vanisher", "Abyss"],
        "27 HEROIC VERSE": ["Monkey Dance", "bloomin' feeling", "Zenius -I- vanisher", "Abyss"],
        "28 BISTROVER": ["Monkey Dance", "bloomin' feeling", "Zenius -I- vanisher", "Abyss"],
        "29 CastHour": ["Monkey Dance", "IDC feat.REVERBEE (Mo'Cuts Ver)", "Zenius -I- vanisher", "Abyss"],
        "30 RESIDENT": ["Release The Music", "IDC feat.REVERBEE (Mo'Cuts Ver)", "Do What You Want", "Ariah"],
        "31 EPOLIS": ["Mel", "IDC feat.REVERBEE (Mo'Cuts Ver)", "Zenius -I- vanisher", "Ariah"],
        "32 Pinky Crush": ["Iris", "WHA", "Zenius -I- vanisher", "Ariah"],
    },

    "3rd Dan": {
        "7th style": ["Voltage (feat. Hidemaru)", "Spin the disc", "starmine", "L'amour et la liberté"],
        "8th style": ["thunder", "starmine", "Spin the disc", "MUSIC TO YOUR HEAD"],
        "9th style": ["STAR FIELD", "PLEASE DON'T GO", "BRIGHTNESS DARKNESS", "starmine"],
        "10th style": ["thunder", "STAR FIELD", "Silvia Drive", "pandora"],
        "11 IIDX RED": ["BLOCKS", "thunder", "STAR FIELD", "Silvia Drive"],
        "12 HAPPY SKY": ["MARIA (I believe... )", "thunder", "STAR FIELD", "Silvia Drive"],
        "13 DistorteD": ["Spin the disc", "thunder", "Broadbanded", "Silvia Drive"],
        "14 GOLD": ["thunder", "嘆きの樹", "Presto", "Spin the disc"],
        "15 DJ TROOPERS": ["thunder", "嘆きの樹", "Presto", "CaptivAte～裁き～"],
        "16 EMPRESS": ["thunder", "嘆きの樹", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "17 SIRIUS": ["高高度降下低高度開傘", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "18 Resort Anthem": ["高高度降下低高度開傘", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "19 Lincle": ["高高度降下低高度開傘", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "20 tricoro": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "21 SPADA": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "22 PENDUAL": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "23 copula": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "24 SINOBUZ": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "25 CANNON BALLERS": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "26 Rootage": ["かげぬい ～ Ver.BENIBOTAN ～", "Presto", "BRIDAL FESTIVAL !!!", "CaptivAte～裁き～"],
        "27 HEROIC VERSE": ["Flip Flap", "梅雪夜", "Presto", "Music is The Answer"],
        "28 BISTROVER": ["梅雪夜", "IDC feat.REVERBEE (Mo'Cuts Ver)", "Presto", "Music is The Answer"],
        "29 CastHour": ["梅雪夜", "Red. by Jack Trance", "Presto", "Music is The Answer"],
        "30 RESIDENT": ["Seaside Labyrinth", "Xlø", "Forgetting Machine", "N.O."],
        "31 EPOLIS": ["SAMSARA", "Seaside Labyrinth", "SPEED DEMON", "龍と少女とデコヒーレンス"],
        "32 Pinky Crush": ["SAMSARA", "Seaside Labyrinth", "SPEED DEMON", "into the battlefield"],
    },

    "4th Dan": {
        "7th style": ["ABSOLUTE", "era (nostalmix)", "Blueberry Stream", "DIVE ～INTO YOUR HEART～"],
        "8th style": ["ABSOLUTE", "era (nostalmix)", "Blueberry Stream", "Smoke"],
        "9th style": ["MARIA (I believe... )", "era (nostalmix)", "Happy Wedding", "Frozen Ray (original mix)"],
        "10th style": ["CARRY ON NIGHT (English version)", "era (nostalmix)", "R5", "BABY LOVE"],
        "11 IIDX RED": ["MUSIC TO YOUR HEAD", "era (nostalmix)", "R5", "SPEEDY CAT"],
        "12 HAPPY SKY": ["ABSOLUTE", "vault of heaven", "era (nostalmix)", "R5"],
        "13 DistorteD": ["era (nostalmix)", "ABSOLUTE", "vault of heaven", "R5"],
        "14 GOLD": ["era (nostalmix)", "虹色", "ALFARSHEAR 双神威に廻る夢", "R5"],
        "15 DJ TROOPERS": ["era (nostalmix)", "虹色", "ALFARSHEAR 双神威に廻る夢", "R5"],
        "16 EMPRESS": ["era (nostalmix)", "虹色", "ALFARSHEAR 双神威に廻る夢", "R5"],
        "17 SIRIUS": ["era (nostalmix)", "虹色", "thunder", "R5"],
        "18 Resort Anthem": ["era (nostalmix)", "虹色", "thunder", "R5"],
        "19 Lincle": ["era (nostalmix)", "虹色", "thunder", "R5"],
        "20 tricoro": ["era (nostalmix)", "虹色", "thunder", "R5"],
        "21 SPADA": ["era (nostalmix)", "虹色", "thunder", "R5"],
        "22 PENDUAL": ["era (nostalmix)", "虹色", "BEAUTIFUL ANGEL", "R5"],
        "23 copula": ["era (nostalmix)", "虹色", "TA・DA☆YO・SHI", "R5"],
        "24 SINOBUZ": ["era (nostalmix)", "虹色", "TA・DA☆YO・SHI", "R5"],
        "25 CANNON BALLERS": ["era (nostalmix)", "虹色", "TA・DA☆YO・SHI", "R5"],
        "26 Rootage": ["era (nostalmix)", "虹色", "TA・DA☆YO・SHI", "R5"],
        "27 HEROIC VERSE": ["era (nostalmix)", "虹色", "TA・DA☆YO・SHI", "R5"],
        "28 BISTROVER": ["ÆTHER", "虹色", "TA・DA☆YO・SHI", "QQQ"],
        "29 CastHour": ["虹色", "ÆTHER", "PLASMA", "QQQ"],
        "30 RESIDENT": ["口カラ凸ゲキ", "打打打打打打打打打打", "Wolf 1061", "QQQ"],
        "31 EPOLIS": ["口カラ凸ゲキ", "Theory", "Wolf 1061", "Egret and Willow"],
        "32 Pinky Crush": ["The Commanders", "smooooch・∀・ (Snail's House Remix)", "HAT TRICK", "HYPER BOUNDARY GATE"],
    },

    "5th Dan": {
        "7th style": ["sync", "Presto", "G2", "QQQ"],
        # 8th–15th include random selections (4 of 5). Listing full candidate pools:
        "8th style": ["sync", "Presto", "G2", "Real", "Frozen Ray (original mix)"],
        "9th style": ["sync", "Golden Horn", "e-motion 2003 -romantic extra-", "ZERO-ONE", "JIVE INTO THE NIGHT"],
        "10th style": ["sync", "Golden Horn", "Sweet Sweet ♡ Magic", "SHOOTING STAR", "JIVE INTO THE NIGHT"],
        "11 IIDX RED": ["sync", "LOVE♥SHINE", "Sweet Sweet ♡ Magic", "Presto", "太陽～T・A・I・Y・O～"],
        "12 HAPPY SKY": ["sync", "LOVE♥SHINE", "POODLE", "LESSON 5", "太陽～T・A・I・Y・O～"],
        "13 DistorteD": ["sync", "LOVE♥SHINE", "Sun Field", "LESSON 5", "太陽～T・A・I・Y・O～"],
        "14 GOLD": ["sync", "LOVE♥SHINE", "Don't be afraid myself", "STAR FIELD", "JIVE INTO THE NIGHT"],
        "15 DJ TROOPERS": ["sync", "LOVE♥SHINE", "ANDROMEDA", "STAR FIELD", "JIVE INTO THE NIGHT"],
        "16 EMPRESS": ["ANDROMEDA", "sync", "STAR FIELD", "LESSON 5"],
        "17 SIRIUS": ["smooooch・∀・", "abstract", "STAR FIELD", "NEW GENERATION -もう、お前しか見えない-"],
        "18 Resort Anthem": ["smooooch・∀・", "abstract", "Bounce Bounce Bounce", "NEW GENERATION -もう、お前しか見えない-"],
        "19 Lincle": ["smooooch・∀・", "NEW GENERATION -もう、お前しか見えない-", "ABSOLUTE", "abstract"],
        "20 tricoro": ["smooooch・∀・", "snow storm", "華爛漫 -Flowers-", "NEW GENERATION -もう、お前しか見えない-"],
        "21 SPADA": ["smooooch・∀・", "Infinite cave", "華爛漫 -Flowers-", "NEW GENERATION -もう、お前しか見えない-"],
        "22 PENDUAL": ["smooooch・∀・", "Infinite cave", "Mermaid girl", "NEW GENERATION -もう、お前しか見えない-"],
        "23 copula": ["smooooch・∀・", "Mermaid girl", "MIRACLE MEETS", "NEW GENERATION -もう、お前しか見えない-"],
        "24 SINOBUZ": ["Follow Tomorrow", "Mermaid girl", "MIRACLE MEETS", "NEW GENERATION -もう、お前しか見えない-"],
        "25 CANNON BALLERS": ["Follow Tomorrow", "Mermaid girl", "Todestrieb", "NEW GENERATION -もう、お前しか見えない-"],
        "26 Rootage": ["starmine", "Punch Love♡仮面", "もっと！モット！ときめき feat. 松下", "NEW GENERATION -もう、お前しか見えない-"],
        "27 HEROIC VERSE": ["starmine", "Punch Love♡仮面", "もっと！モット！ときめき feat. 松下", "NEW GENERATION -もう、お前しか見えない-"],
        "28 BISTROVER": ["starmine", "Punch Love♡仮面", "もっと！モット！ときめき feat. 松下", "NEW GENERATION -もう、お前しか見えない-"],
        "29 CastHour": ["Here We Are", "Queen's Tragedy", "もっと！モット！ときめき feat. 松下", "Dr. Chemical & Killing Machine"],
        "30 RESIDENT": ["CROSSROAD", "LIGHTNING STRIKES", "DISPARATE", "Dr. Chemical & Killing Machine"],
        "31 EPOLIS": ["Sugarplum", "Critical Crystal", "Nocturnal 2097", "東京神話"],
        "32 Pinky Crush": ["Sugarplum", "CUE CUE RESCUE", "Nocturnal 2097", "Dr. Chemical & Killing Machine"],
    },

    "6th Dan": {
        "7th style": ["Tomorrow Perfume", "Colors (radio edit)", "DXY!", "Regulus"],
        "8th style": ["rainbow flyer", "Colors (radio edit)", "DXY!", "murmur twins"],
        "9th style": ["Colors (radio edit)", "Karma", "murmur twins", "Distress"],
        "10th style": ["Giudecca", "Colors (radio edit)", "Lucy", "murmur twins"],
        "11 IIDX RED": ["spiral galaxy", "Colors (radio edit)", "murmur twins", "Distress"],
        "12 HAPPY SKY": ["Sphere", "murmur twins", "quasar", "Colors (radio edit)"],
        "13 DistorteD": ["Apocalypse～dirge of swans～", "murmur twins", "quasar", "Colors (radio edit)"],
        "14 GOLD": ["HIGH", "Be quiet", "Regulus", "Colors (radio edit)"],
        "15 DJ TROOPERS": ["traces", "CaptivAte～浄化～", "MOON", "Distress"],
        "16 EMPRESS": ["traces", "CaptivAte2～覚醒～", "MOON", "ZERO-ONE"],
        "17 SIRIUS": ["THANK YOU FOR PLAYING", "カゴノトリ～弐式～", "Rise'n Beauty", "bloomin' feeling"],
        "18 Resort Anthem": ["THANK YOU FOR PLAYING", "カゴノトリ～弐式～", "Rise'n Beauty", "bloomin' feeling"],
        "19 Lincle": ["THANK YOU FOR PLAYING", "カゴノトリ～弐式～", "Rise'n Beauty", "bloomin' feeling"],
        "20 tricoro": ["THANK YOU FOR PLAYING", "黒髪乱れし修羅となりて", "Be quiet", "bloomin' feeling"],
        "21 SPADA": ["FLOWER", "黒髪乱れし修羅となりて", "Be quiet", "bloomin' feeling"],
        "22 PENDUAL": ["Devilz Sacrifice -贖罪の羊-", "黒髪乱れし修羅となりて", "Frozen Ray (original mix)", "bloomin' feeling"],
        "23 copula": ["Apocalypse～dirge of swans～", "黒髪乱れし修羅となりて", "naughty girl@Queen's Palace", "bloomin' feeling"],
        "24 SINOBUZ": ["New Decade IIDX Edition", "黒髪乱れし修羅となりて", "Rise'n Beauty", "bloomin' feeling"],
        "25 CANNON BALLERS": ["quasar", "バンブーソード・ガール", "DIAVOLO", "bloomin' feeling"],
        "26 Rootage": ["紅牡丹", "Bounce Bounce Bounce", "旅人リラン", "rottel-the-Mercury"],
        "27 HEROIC VERSE": ["NINJA IS DEAD IIDX ver.", "Bounce Bounce Bounce", "旅人リラン", "rottel-the-Mercury"],
        "28 BISTROVER": ["Boomy and The Boost", "Digitank System", "Sphere", "Hurry Hurry"],
        "29 CastHour": ["Amazing Mirage", "Hello Happiness", "Sphere", "Hurry Hurry"],
        "30 RESIDENT": ["Turii ～Panta rhei～", "Digitank System", "Sphere", "Hurry Hurry"],
        "31 EPOLIS": ["satfinal", "黒髪乱れし修羅となりて", "Push on Beats!～音ゲの国のeX-ストリーマー～", "IXION"],
        "32 Pinky Crush": ["Boomy and The Boost", "青の洞窟", "POLꞰAMAИIA", "IXION"],
    },

    "7th Dan": {
        "7th style": ["V", "Y31", "B4U", "THE SAFARI"],
        "8th style": ["V", "Red Nikita", "LAB", "THE SAFARI"],
        "9th style": ["V", "NEMESIS", "ACT", "THE SAFARI"],
        "10th style": ["V", "Debtty Daddy", "Abyss -The Heavens Remix-", "THE SAFARI"],
        "11 IIDX RED": ["RED ZONE", "V", "Abyss -The Heavens Remix-", "THE SAFARI"],
        "12 HAPPY SKY": ["Xepher", "V", "RED ZONE", "THE SAFARI"],
        "13 DistorteD": ["Aurora", "Quickening", "Little Little Princess", "THE SAFARI"],
        "14 GOLD": ["rainbow rainbow", "Concertino in Blue", "smile", "THE SAFARI"],
        "15 DJ TROOPERS": ["FIRE FIRE", "V", "Concertino in Blue", "THE SAFARI"],
        "16 EMPRESS": ["waxing and wanding", "冥", "TROOPERS", "THE SAFARI"],
        "17 SIRIUS": ["B4U(BEMANI FOR YOU MIX)", "Übertreffen", "MENTAL MELTDOWN", "THE SAFARI"],
        "18 Resort Anthem": ["Bloody Tears(IIDX EDITION)", "Übertreffen", "mosaic", "THE SAFARI"],
        "19 Lincle": ["mosaic", "Übertreffen", "Bloody Tears(IIDX EDITION)", "THE SAFARI"],
        "20 tricoro": ["Rising in the Sun(original mix)", "Bloody Tears(IIDX EDITION)", "FIRE FIRE", "THE SAFARI"],
        "21 SPADA": ["Todestrieb", "Bloody Tears(IIDX EDITION)", "FIRE FIRE", "THE SAFARI"],
        "22 PENDUAL": ["Todestrieb", "ΕΛΠΙΣ", "Übertreffen", "THE SAFARI"],
        "23 copula": ["BRAINSTORM", "Twelfth Style", "Übertreffen", "THE SAFARI"],
        "24 SINOBUZ": ["SHADE", "Twelfth Style", "ƒƒƒƒƒ", "THE SAFARI"],
        "25 CANNON BALLERS": ["ANDROMEDA II", "アルストロメリア", "V", "THE SAFARI"],
        "26 Rootage": ["Watch Out Pt.2", "Kung-fu Empire", "Zirkfied", "THE SAFARI"],
        "27 HEROIC VERSE": ["Rave*it!! Rave*it!!", "Kung-fu Empire", "StrayedCatz", "THE SAFARI"],
        "28 BISTROVER": ["Flashes", "Flash Back 90's", "Verflucht", "THE SAFARI"],
        "29 CastHour": ["仮想空間の旅人たち", "Smashing Wedge", "Flash Back 90's", "THE SAFARI"],
        "30 RESIDENT": ["BroGamer", "entelecheia", "Flash Back 90's", "THE SAFARI"],
        "31 EPOLIS": ["HEARTACHE", "ruin of opals", "Rowdy", "THE SAFARI"],
        "32 Pinky Crush": ["華爛漫 -Flowers-", "Devil's Gear", "Tripping Jumping", "THE SAFARI"],
    },

    "8th Dan": {
        "7th style": ["Mr.T.(take me higher)", "stoic", "STILL IN MY HEART", "GET ON BEAT (WILD STYLE)"],
        "8th style": ["symbolic", "stoic", "革命", "GET ON BEAT (WILD STYLE)"],
        "9th style": ["moon_child", "stoic", "one or eight", "GET ON BEAT (WILD STYLE)"],
        "10th style": ["moon_child", "雪月花", "one or eight", "No.13"],
        "11 IIDX RED": ["雪月花", "No.13", "AA", "gigadelic"],
        "12 HAPPY SKY": ["雪月花", "No.13", "moon_child", "gigadelic"],
        "13 DistorteD": ["AA", "1st Samurai", "stoic", "gigadelic"],
        "14 GOLD": ["雪月花", "1st Samurai", "Scripted Connection⇒(H mix)", "gigadelic"],
        "15 DJ TROOPERS": ["The Dirty of Loudness", "電人、暁に斃れる。", "Candy Galy", "Innocent Walls"],
        "16 EMPRESS": ["V₂", "stoic", "少年A", "gigadelic"],
        "17 SIRIUS": ["four pieces of heaven", "天空脳番長危機十六連打", "冥", "gigadelic"],
        "18 Resort Anthem": ["BITTER CHOCOLATE STRIKER", "Session 9 -Chronicles-", "G59", "gigadelic"],
        "19 Lincle": ["Dances with Snow Fairies", "灼熱Beach Side Bunny", "V₂", "gigadelic"],
        "20 tricoro": ["GRADIUS 2012", "Snake Stick", "V₂", "gigadelic"],
        "21 SPADA": ["SOLITON BEAM", "BLACK.by X-Cross Fade", "garden", "gigadelic"],
        "22 PENDUAL": ["Präludium", "KAMIKAZE", "Miracle 5ympho X", "gigadelic"],
        "23 copula": ["リリーゼと炎龍レーヴァテイン", "end of world", "rottel-da-sun", "gigadelic"],
        "24 SINOBUZ": ["Make Me Your Own", "Quickening", "POINT ZERO", "gigadelic"],
        "25 CANNON BALLERS": ["NO LIMIT -オレ達に限界は無い", "革命", "KAMIKAZE", "gigadelic"],
        "26 Rootage": ["疾風迅雷", "廿", "LAB", "S!ck"],
        "27 HEROIC VERSE": ["Let me be your cure", "Feedback", "Apocalypse ～dirge of swans～", "S!ck"],
        "28 BISTROVER": ["Infinity Mirror", "Red. by Jack Trance", "V₂", "S!ck"],
        "29 CastHour": ["Virus Funk", "Daisuke", "忍恋花", "STARLIGHT DANCEHALL"],
        "30 RESIDENT": ["Chewingood!!!", "GOLD RUSH", "Miracle 5ympho X", "Amazing Mirage"],
        "31 EPOLIS": ["GET UP AGAIN", "DENIM", "Miracle 5ympho X", "Fervidex"],
        "32 Pinky Crush": ["BLACK JACKAL", "SigSig", "ちょえちょえまぎか", "BRAINSTORM"],
    },

    "9th Dan": {
        "7th style": ["R壱萬", "Buffalo", "era (step mix)", "NEMESIS"],
        # 8th & 9th style are random sets (4 of 5):
        "8th style": ["sync", "Buffalo", "era (step mix)", "NEMESIS", "Giudecca"],
        "9th style": ["sync", "rottel-da-sun", "quasar", "Macho Gang", "lower world"],
        "10th style": ["EXE", "Innocent Walls", "sync", "quasar"],
        "11 IIDX RED": ["ピアノ協奏曲第１番”蠍火”", "sync", "GENOCIDE", "quasar"],
        "12 HAPPY SKY": ["INAZUMA", "Aurora", "rainbow rainbow", "Innocent Walls"],
        "13 DistorteD": ["tripping contact(teranoid&MC Natsack Remix)", "Aurora", "Concertino in Blue", "Innocent Walls"],
        "14 GOLD": ["KAMAITACHI", "華蝶風雪", "INAZUMA", "waxing and wanding"],
        "15 DJ TROOPERS": ["THE DEEP STRIKER", "G2", "Time to Air", "moon_child"],
        "16 EMPRESS": ["THE DEEP STRIKER", "天空脳番長危機十六連打", "B4U(BEMANI FOR YOU MIX)", "moon_child"],
        "17 SIRIUS": ["INAZUMA", "No.13", "Session 1 -Genesis-", "moon_child"],
        "18 Resort Anthem": ["Raison d'être～交差する宿命～", "Anisakis -somatic mutation type\"Forza\"-", "ANTHEM LANDING", "moon_child"],
        "19 Lincle": ["MENTAL MELTDOWN", "Xepher", "Sun Field", "雪月花"],
        "20 tricoro": ["SHADE", "旅人リラン", "Pollinosis", "The Sampling Paradise"],
        "21 SPADA": ["ZED", "Bounce Bounce Bounce", "旅人リラン", "The Sampling Paradise"],
        "22 PENDUAL": ["Holic", "Just a Little Smile", "rumrum triplets", "The Sampling Paradise"],
        "23 copula": ["Acid Pumper", "Chrono Diver -PENDULUMs-", "Cookie Bouquets", "The Sampling Paradise"],
        "24 SINOBUZ": ["rainbow guitar weeps", "Kailua (HCN Ver.)", "旅人リラン", "The Sampling Paradise"],
        "25 CANNON BALLERS": ["Line 4 Ruin", "Golden Palms†", "four pieces of heaven", "Scripted Connection⇒ A mix"],
        "26 Rootage": ["The Dirty of Loudness", "naughty girl@Queen's Palace", "Cookie Bouquets", "SAY BAY"],
        "27 HEROIC VERSE": ["Battleground", "Just a Little Smile", "ALBA -黎明-", "少年A"],
        "28 BISTROVER": ["Override", "BroGamer", "ALBA -黎明-", "少年A"],
        "29 CastHour": ["鴉", "Theory", "Night! Night! Night!", "Todestrieb"],
        "30 RESIDENT": ["Burning Flame", "nostos", "& Intelligence", "Todestrieb"],
        "31 EPOLIS": ["City Never Sleeps (IIDX Edition)", "chaos eater -IIDX edition-", "In the Blackest Den", "禊"],
        "32 Pinky Crush": ["君のハートにロックオン", "C-C-C-N-N-N", "錬成人間トリコロイダー", "禊"],
    },

    "10th Dan": {
        "7th style": ["Holic", "Colors (radio edit)", "V", "A"],
        # 8th & 9th style are random sets (4 of 7):
        "8th style": ["Holic", "V", "Colors (radio edit)", "Spica", "A", "murmur twins", "xenon"],
        "9th style": ["V", "Colors (radio edit)", "Spica", "A", "PLEASE DON'T GO", "moon_child", "one or eight"],
        "10th style": ["Spica", "One More Lovely", "moon_child", "No.13"],
        "11 IIDX RED": ["Colors (radio edit)", "One More Lovely", "V", "AA"],
        "12 HAPPY SKY": ["Scripted Connection⇒", "FAKE TIME", "ピアノ協奏曲第１番”蠍火”", "One More Lovely"],
        "13 DistorteD": ["Scripted Connection⇒", "No.13", "DUE TOMORROW", "One More Lovely"],
        "14 GOLD": ["電人、暁に斃れる。", "LASER CRUSTER", "AA", "Candy Galy"],
        "15 DJ TROOPERS": ["Scripted Connection⇒ A mix", "oratio", "Sense 2007", "AA"],
        "16 EMPRESS": ["Scripted Connection⇒ A mix", "FIRE FIRE", "ピアノ協奏曲第１番”蠍火”", "AA"],
        "17 SIRIUS": ["Scripted Connection⇒ A mix", "不沈艦CANDY", "Colorful Cookie", "AA"],
        "18 Resort Anthem": ["mosaic", "Colorful Cookie", "ワルツ第17番 ト短調”大犬のワルツ”", "GOLDEN CROSS"],
        "19 Lincle": ["ƒƒƒƒƒ", "Colorful Cookie", "ワルツ第17番 ト短調”大犬のワルツ”", "GOLDEN CROSS"],
        "20 tricoro": ["恋する☆宇宙戦争っ!!", "Sense 2007", "Colorful Cookie", "reunion"],
        "21 SPADA": ["NNRT", "Sense 2007", "Colorful Cookie", "reunion"],
        "22 PENDUAL": ["Adularia", "ワルツ第17番 ト短調”大犬のワルツ”", "不沈艦CANDY", "The Limbo"],
        "23 copula": ["invoker", "Colorful Cookie", "Proof of the existence", "reunion"],
        "24 SINOBUZ": ["GAIA", "Gravigazer", "Colorful Cookie", "reunion"],
        "25 CANNON BALLERS": ["紫陽花 -AZISAI-", "IMPLANTATION", "FIRE FIRE", "Broken Sword"],
        "26 Rootage": ["Rave Cannon", "IMPLANTATION", "FIRE FIRE", "reunion"],
        "27 HEROIC VERSE": ["POSSESSION", "FIRE FIRE", "Colorful Cookie", "reunion"],
        "28 BISTROVER": ["Super Rush", "Sense 2007", "Colorful Cookie", "AA -rebuild-"],
        "29 CastHour": ["DARK LEGACY", "Sense 2007", "Colorful Cookie", "BEAT PRISONER"],
        "30 RESIDENT": ["Rampage", "Level 2", "GENE", "BEAT PRISONER"],
        "31 EPOLIS": ["Nightmare before oversleep", "Level 2", "entelecheia", "BEAT PRISONER"],
        "32 Pinky Crush": ["T-REX vs Velociraptor (In the Far east euphoria)", "焱影", "BITTER CHOCOLATE STRIKER", "NITROUS CANNON"],
    },

    "Chuuden": {
        "23 copula": ["BITTER CHOCOLATE STRIKER", "Reflux", "MENDES", "DIAMOND CROSSING"],
        "24 SINOBUZ": ["ピアノ協奏曲第１番”蠍火”", "Reflux", "JOMANDA", "MENDES"],
        "25 CANNON BALLERS": ["Godspeed", "轟け！恋のビーンボール！！", "Reflux", "MENDES"],
        "26 Rootage": ["Sky High", "Snake Stick", "Bad Maniacs", "MENDES"],
        "27 HEROIC VERSE": ["Snakey Kung-fu", "199024club -Re:BounceKiller-", "Bad Maniacs", "MENDES"],
        "28 BISTROVER": ["TRIUMPH", "Snake Stick", "Bad Maniacs", "Sigmund"],
        "29 CastHour": ["Shooting Fireball", "Dynamite", "金野火織の金色提言", "Sigmund"],
        "30 RESIDENT": ["Smashing Wedge", "LOCUS OF THE TRAVEL", "天空の夜明け", "perditus†paradisus"],
        "31 EPOLIS": ["ALTERNATOR", "voltississimo", "天空の夜明け", "perditus†paradisus"],
        "32 Pinky Crush": ["お菓子の王国", "天空の夜明け", "WHA", "Bad Encryption"],
    },

    "Kaiden": {
        "13 DistorteD": ["rage against usual", "嘆きの樹", "ピアノ協奏曲第１番”蠍火”", "冥"],
        "14 GOLD": ["FIRE FIRE", "嘆きの樹", "ピアノ協奏曲第１番”蠍火”", "冥"],
        "15 DJ TROOPERS": ["ピアノ協奏曲第１番”蠍火”", "嘆きの樹", "MENDES", "冥"],
        "16 EMPRESS": ["嘆きの樹", "MENDES", "卑弥呼", "冥"],
        "17 SIRIUS": ["quell～the seventh slave～", "嘆きの樹", "卑弥呼", "冥"],
        "18 Resort Anthem": ["Bad Maniacs", "嘆きの樹", "卑弥呼", "冥"],
        "19 Lincle": ["嘆きの樹", "perditus†paradisus", "卑弥呼", "冥"],
        "20 tricoro": ["嘆きの樹", "天空の夜明け", "卑弥呼", "冥"],
        "21 SPADA": ["嘆きの樹", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "22 PENDUAL": ["嘆きの樹", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "23 copula": ["perditus†paradisus", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "24 SINOBUZ": ["perditus†paradisus", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "25 CANNON BALLERS": ["嘆きの樹", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "26 Rootage": ["嘆きの樹", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "27 HEROIC VERSE": ["嘆きの樹", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "28 BISTROVER": ["EMERALDAS", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "29 CastHour": ["EMERALDAS", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "30 RESIDENT": ["EMERALDAS", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "31 EPOLIS": ["EMERALDAS", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
        "32 Pinky Crush": ["Somnidiscotheque", "灼熱Beach Side Bunny", "卑弥呼", "冥"],
    },
}
